import Mathlib.AlgebraicGeometry.Scheme
import Mathlib.Data.Complex.Basic
import Mathlib.Algebra.Module.Submodule.Basic

set_option linter.unusedVariables false
set_option diagnostics true
set_option diagnostics.threshold 5000

namespace VarietyDefinition

open AlgebraicGeometry Scheme Complex

/-!
## Hodge conjecture scaffolding (no axioms)

Mathlib does not currently provide a full development of singular cohomology of complex varieties
or the cycle class map in the generality needed for the Hodge conjecture. To keep this repository
`axiom`-free, we *parameterize* the statement by a package of data (`HodgeData`) containing the
relevant objects and maps.
-/

/-- A structure representing a smooth projective variety over a field. -/
structure SmoothProjectiveVariety (K : Type*) [Field K] where
  /-- The underlying scheme. -/
  X : Scheme
  /-- The scheme is smooth. -/
  is_smooth : Prop
  /-- The scheme is projective. -/
  is_projective : Prop

/--
All the extra objects needed to state the Hodge conjecture for a fixed variety `X`.

This is *data*, not an assertion that such objects exist.
-/
structure HodgeData (X : SmoothProjectiveVariety ℂ) where
  /-- Rational cohomology groups `H^n(X, ℚ)` (as `ℚ`-vector spaces). -/
  cohomologyQ : ℕ → Type*
  [cohomologyQ_add : ∀ n, AddCommGroup (cohomologyQ n)]
  [cohomologyQ_module : ∀ n, Module ℚ (cohomologyQ n)]

  /-- Complex cohomology groups `H^n(X, ℂ)` (as `ℂ`-vector spaces). -/
  cohomologyC : ℕ → Type*
  [cohomologyC_add : ∀ n, AddCommGroup (cohomologyC n)]
  [cohomologyC_moduleC : ∀ n, Module ℂ (cohomologyC n)]
  /-- We also view complex cohomology as a `ℚ`-module (restriction of scalars). -/
  [cohomologyC_moduleQ : ∀ n, Module ℚ (cohomologyC n)]

  /-- Extension of scalars `H^n(X, ℚ) → H^n(X, ℂ)` (as a `ℚ`-linear map). -/
  extensionOfScalarsQC : ∀ n : ℕ, cohomologyQ n →ₗ[ℚ] cohomologyC n

  /-- Target type for a Hodge decomposition map. -/
  HodgeComponent : Type*
  /-- A chosen Hodge decomposition map for each degree. -/
  hodgeDecomposition : ∀ n : ℕ, cohomologyC n → HodgeComponent

  /-- The `ℚ`-subspace of Hodge classes in degree `2p`. -/
  hodgeClass : ∀ p : ℕ, Submodule ℚ (cohomologyQ (2 * p))

  /-- Algebraic cycles of codimension `p`. -/
  algebraicCycle : ℕ → Type*
  /-- Cycle class map `Z^p(X) → H^{2p}(X, ℚ)`. -/
  cycleClass : ∀ p : ℕ, algebraicCycle p → cohomologyQ (2 * p)

  /-- The `ℚ`-subspace of cohomology generated by algebraic cycles. -/
  algebraicCohomology : ∀ p : ℕ, Submodule ℚ (cohomologyQ (2 * p))

end VarietyDefinition
